import './normalize.css'
import './variables.css'
import './fonts.css'
import './globals.css'
import './utils.css'

import './components/header.css'
import './components/chat.css'
import './components/footer.css'
import './components/message.css'
